{"describe": "Open access encyclopaedia, based on Kluwer edition of 2002.", "link": "http://www.encyclopediaofmath.org/", "title": "Encyclopedia of Mathematics "}
{"describe": "Searchable directory, arranged by field, of equations, constants, symbols and SI units. Also features LaTEX utilities, software links.", "link": "http://www.equationsheet.com/", "title": "Equations "}
{"describe": "An excerpt from the 30th Edition of the CRC Standard Mathematical Tables and Formulas, covering the area of Geometry (minus differential geometry), by Silvio Levy.", "link": "http://geom.math.uiuc.edu/docs/reference/CRC-formulas/", "title": "Geometry Formulas and Facts "}
{"describe": "Spreadsheets on the distribution of 1000 common math terms as used in K-12th grade mathematics textbooks over the last 30 years. Analysis in English, Spanish and French.", "link": "http://www.k-12math.info/", "title": "K-12 math textbook content analysis "}
{"describe": "A large , free online lists of mathematics formulas. Collection of all basic and advanced formulas related to mathematics.", "link": "http://www.sciencehq.com/math-formulas/", "title": "Math formulas "}
{"describe": "An online interactive Math textbook.", "link": "http://mathopenref.com/", "title": "Math Open Reference "}
{"describe": "An electronic archive of articles by Karl Dahlke on topics ranging from high school geometry up to graduate level topology.", "link": "http://www.mathreference.com/", "title": "The Math Reference Project "}
{"describe": "Mathematics lecture videos and talks taken from The Pacific Institute for the Mathematical Sciences (PIMS) member universities and around the world.", "link": "http://www.mathtube.org/", "title": "Math Tube "}
{"describe": "Exposition of the basic concepts and theory of various subjects including matrix theory, calculus, modern abstract algebra, linear algebra, plane analytic geometry and solid analytic geometry.", "link": "http://solitaryroad.com/math.html", "title": "Mathematics Notes "}
{"describe": "Result of a project to provide a modern revision of Abramowitz and Stegun\u2019s \"Handbook of Mathematical Functions\". The site includes definitions, properties, and graphs of many special functions.", "link": "http://dlmf.nist.gov/", "title": "NIST Digital Library of Mathematical Functions "}
{"describe": "Tables for Greek and Latin number values alone and as a part of other words.", "link": "http://phrontistery.info/numbers.html", "title": "Numerical Prefixes "}
{"describe": "Identify a sequence by entering few terms in the sequence. Additional information includes examples, formulas, and related links.", "link": "http://oeis.org/", "title": "The On-Line Encyclopedia of Integer Sequences (OEIS) "}
{"describe": "A collaborative encyclopaedia with entries contributed under the GNU Free Documentation License.", "link": "http://planetmath.org/", "title": "PlanetMath "}
{"describe": "Online resource for the mathematics community: links library, bookstore, quotes, and online articles.", "link": "http://www.mathacademy.com/pr/index.asp", "title": "Platonic Realms "}
{"describe": "For polynomials of degrees up to 50, generated using the Euler-Maclaurin method.", "link": "http://polysum.tripod.com/", "title": "Summation Formulae "}
{"describe": "A large collection of useful mathematical problem-solving techniques.", "link": "http://www.tricki.org/", "title": "Tricki "}
{"describe": "Web Formulas provides collections of formulas used in math, physics and chemistry.", "link": "http://www.web-formulas.com/", "title": "Web Formulas "}
{"describe": "Free crowd-sourced encyclopedia. Covers number systems, different math fields, foundations, history, applications, and famous problems.", "link": "http://en.wikipedia.org/wiki/Portal:Mathematics", "title": "Wikipedia: Mathematics Portal "}
{"describe": "Includes advanced formulas and visualizations of various equations, such as elliptic curves.", "link": "http://functions.wolfram.com/", "title": "Wolfram: Mathematical Functions "}
